### PR TITLE
Fix package.json

### PR DESCRIPTION
**Pull request by dbkaplun**

### CODE REVIEW

**Comment by JasonMore** [comment]
@dbkaplun Why did you change the post install? It's going to break the build when checked into master. 

@blame_jpro hold on this one for now

**Comment by JasonMore** [comment]
Correction @xjpro hold on this for now

**Comment by dbkaplun** [comment]
Hmm, both tests passed. Are you sure? How can I test?

**Comment by xjpro** [comment]
Had to fix the test command for integration tests but otherwise looked good. Merged.

**Pull request merged**
