### PR TITLE
Update bower.json dependencies and fix the issues working with sails.io.js 0.11.x

### PR DESCRIPTION
**Pull request by andyhu**
#4

### CODE REVIEW

**Comment by xjpro** [comment]
Hey, thanks for the update! I plan on taking a look at this today or tomorrow. It looks like the changes you made might have broken the build/tests so I may just do my own fixes instead of merging this PR, unless you want to fix up whatever issue is causing the break.

**Comment by andyhu** [comment]
Hi, thanks for your reply. Not sure why the test is failed. For your info, I'm currently using it with sails v0.11.0-rc6 and everything works fine

**Comment by xjpro** [comment]
Been working on this today. Before doing anything I created a release for the current code base (1.0.0) and actually used a tag this time so we can not pull in the latest if undesired. I did this because Sails 0.11 is not quite yet released and I didn't want to force anyone onto it just yet. It looks like it's nearly ready though so it's good we're looking at necessary changes now.

It looks to me like some of the testing, specifically in the /example app, is still on Sails 0.10. This is why the tests appear to be failing. We'll need to update the dependencies for the /example app, which is where integration tests run.

**Comment by xjpro** [comment]
I ended up having to do some changes to both the unit and integration tests. The new version has some slightly breaking changes. The 0.11 compatible version is now available as v1.1.0. Here's the full commit: https://github.com/angular-resource-sails/angular-resource-sails/commit/36a2425358c43669ead0a2d2e1f4f984ccd10a84

**Pull request closed without merging**
